### ISSUE TITLE
Doesn't work on Ubuntu 16.04 properly

### ISSUE THREAD

**Issue by vaisov** [jasonhancock/nagios-memory#7]
Returns `0% used`
and also a warning: `Redundant argument in sprintf at check_mem.pl line 132`

**Comment by vaisov** [comment]
Sorry, my bad. I did test in on machine with 192GB of RAM, that's why it showed 0% :)

**Comment by jasonhancock** [comment]
pushed a fix to address the `Redundant argument in sprintf at check_mem.pl line 132` issue.
